"""Validate temporal_track (accumulative per-camera tracking) and resample_to_points.

A single-camera speckle sequence is generated by warping frame 0 with a KNOWN
cumulative affine, so the cumulative node displacement is analytic. temporal_track
must recover ``U_accum`` on the fixed reference mesh; resample_to_points must
interpolate a scattered field onto arbitrary query points NaN-aware.
"""

from __future__ import annotations

import numpy as np
import pytest
from scipy.ndimage import gaussian_filter

from al_dic_3d.matching.primitives import make_local_dicpara
from al_dic_3d.matching.temporal import (
    build_grid_mesh,
    resample_to_points,
    temporal_track,
)

cv2 = pytest.importorskip("cv2")


def _speckle(h: int, w: int, sigma: float = 2.3, seed: int = 11) -> np.ndarray:
    rng = np.random.default_rng(seed)
    f = gaussian_filter(rng.standard_normal((h, w)), sigma=sigma, mode="nearest")
    f -= f.min()
    f /= f.max()
    return 20.0 + 215.0 * f


def _affine_k(k: int) -> np.ndarray:
    """Small cumulative affine at frame k (identity at k=0): slight stretch + shift."""
    a = 1.0 + 0.0008 * k
    tx, ty = 0.35 * k, 0.18 * k
    return np.array([[a, 0.0, tx], [0.0, a, ty], [0.0, 0.0, 1.0]], dtype=np.float64)


def _warp(img: np.ndarray, M: np.ndarray) -> np.ndarray:
    h, w = img.shape
    return cv2.warpPerspective(img, M, (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REFLECT)


def _apply(M: np.ndarray, pts: np.ndarray) -> np.ndarray:
    ph = np.column_stack([pts, np.ones(len(pts))])
    q = ph @ M.T
    return q[:, :2] / q[:, 2:3]


def test_temporal_track_recovers_cumulative_affine():
    h = w = 260
    n_frames = 4
    f0 = _speckle(h, w)
    frames = [f0] + [_warp(f0, _affine_k(k)) for k in range(1, n_frames)]

    para = make_local_dicpara(img_size=(h, w), roi=(40, w - 40, 40, h - 40), winsize=32)
    mesh = build_grid_mesh(para, h, w)
    coords = np.asarray(mesh.coordinates_fem, dtype=np.float64)

    tf = temporal_track(frames, mesh, para)

    assert tf.n_frames == n_frames
    assert np.allclose(tf.ref_coords, coords, atol=1e-6)
    assert np.allclose(tf.u_accum[0], 0.0)  # reference frame

    for k in range(1, n_frames):
        gt = _apply(_affine_k(k), coords) - coords  # analytic cumulative displacement
        good = tf.valid[k]
        err = np.linalg.norm(tf.u_accum[k][good] - gt[good], axis=1)
        assert good.mean() > 0.9, f"frame {k}: only {good.mean():.0%} nodes valid"
        assert np.median(err) < 0.05, f"frame {k}: median err {np.median(err):.3f}px"


def test_resample_to_points_linear_field_is_exact():
    # A field that is exactly affine in (x, y) is reproduced exactly by linear interp.
    rng = np.random.default_rng(0)
    ref = rng.uniform(0, 100, size=(200, 2))
    values = np.column_stack([2.0 + 0.3 * ref[:, 0] - 0.1 * ref[:, 1], -1.0 + 0.05 * ref[:, 1]])
    query = rng.uniform(20, 80, size=(50, 2))  # inside the hull
    out = resample_to_points(ref, values, query)
    gt = np.column_stack([2.0 + 0.3 * query[:, 0] - 0.1 * query[:, 1], -1.0 + 0.05 * query[:, 1]])
    assert np.allclose(out, gt, atol=1e-9)


def test_resample_to_points_is_nan_aware():
    ref = np.array([[0.0, 0], [10, 0], [0, 10], [10, 10], [5, 5]], dtype=np.float64)
    values = np.array([[1.0, 0], [1, 0], [1, 0], [1, 0], [np.nan, np.nan]])
    # The NaN node must not corrupt the interior estimate (constant field -> 1).
    out = resample_to_points(ref, values, np.array([[5.0, 5.0]]), fill_nearest=False)
    assert np.allclose(out, [[1.0, 0.0]])


def test_resample_nearest_fill_outside_hull():
    ref = np.array([[0.0, 0], [10, 0], [0, 10], [10, 10]], dtype=np.float64)
    values = np.array([[3.0, 7.0], [3, 7], [3, 7], [3, 7]])
    out = resample_to_points(ref, values, np.array([[20.0, 20.0]]), fill_nearest=True)
    assert np.allclose(out, [[3.0, 7.0]])  # nearest-filled from the constant field
    out_nan = resample_to_points(ref, values, np.array([[20.0, 20.0]]), fill_nearest=False)
    assert np.isnan(out_nan).all()


def test_resample_nan_query_stays_nan_without_crashing():
    # A non-finite query row has no estimate: it must return NaN (not raise), even
    # on the default fill_nearest=True path, and must not discard good rows.
    ref = np.array([[0.0, 0], [10, 0], [0, 10], [10, 10]], dtype=np.float64)
    values = np.array([[3.0, 7.0], [3, 7], [3, 7], [3, 7]])
    query = np.array([[5.0, 5.0], [np.nan, np.nan]])
    out = resample_to_points(ref, values, query, fill_nearest=True)
    assert np.allclose(out[0], [3.0, 7.0])  # finite query still interpolated
    assert np.isnan(out[1]).all()  # NaN query stays NaN (documented contract)
